name: TrEngine CI

on:
  push:
    branches: [ "main", "testing" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential xorg-dev libglu1-mesa-dev xvfb libgl1-mesa-dri

    - name: Generate Projects (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        chmod +x GenerateProjects.sh
        chmod +x vendor/bin/premake/Linux/premake5
        ./GenerateProjects.sh

    - name: Build Engine (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: make config=release

    - name: Run Headless Test (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        export TRENGINE_CI=1
        xvfb-run -a -s "-screen 0 1280x720x24" ./bin/Release-linux-x86_64/Sandbox/Sandbox

    - name: Add MSBuild to PATH (Windows)
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v2

    - name: Generate Projects (Windows)
      if: matrix.os == 'windows-latest'
      run: .\GenerateProject.bat

    - name: Build Engine (Windows)
      if: matrix.os == 'windows-latest'
      run: msbuild TrEngine.sln /property:Configuration=Release

    - name: Run Headless Test (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $env:TRENGINE_CI="1"
        .\bin\Release-windows-x86_64\Sandbox\Sandbox.exe
